Repository VisualText/vscode-nlp, pull requests merged in 2020-12, with the labels that each got.

#136 VSCODE-NLP-071 context sensitive pass sequence menu and icon items
  package.json
  src/logfile.ts
  src/sequenceView.ts
Labels: enhancement

#138 VSCODE-NLP-072 Added refresh sequence after each run
  src/nlp.ts
Labels: bug

#139 VSCODE-NLP-072 Bug fix for parsing log files.
  src/logfile.ts
Labels: bug

#140 VSCODE-NLP-074 Add status bar fired/built mode
  src/dirfuncs.ts
  src/logfile.ts
  src/nlp.ts
  src/status.ts
Labels: enhancement

#141 VSCODE-NLP-075 Full function snippets for nlp++
  snippets/nlp.json
Labels: enhancement

#143 VSCODE-NLP-076 Handle syntax error display better and fixed mouse overs
  package.json
  src/logView.ts
  src/nlp.ts
Labels: bug

#144 VSCODE-NLP-077 fix highlight bug and missing icon
  package.json
  src/logfile.ts
Labels: bug

#147 VSCODE-NLP-078 New analyzer folder setup fixed, set highlight to FIRE…
  src/status.ts
  src/visualText.ts
Labels: bug

#148 VSCODE-NLP-079 Moves txxt and kb files with sequence pass move
  src/sequence.ts
Labels: enhancement

#149 VSCODE-NLP-080 can delete files from the output view
  fileicons/vs_nlp-icon-theme.json
  package.json
  src/logView.ts
  src/nlp.ts
  src/outputView.ts
  src/sequence.ts
  src/sequenceView.ts
  src/textFile.ts
  syntaxes/kb.tmLanguage.json
  syntaxes/kbb.tmLanguage.json
Labels: enhancement

#151 VSCODE-NLP-082 Add selected text search in nlp files
  package.json
  src/command.ts
  src/nlp.ts
  src/sequenceView.ts
Labels: enhancement

#152 VSCODE-NLP-083 Added generate rule to *.txt files
  package.json
  snippets/nlp.json
  src/analyzer.ts
  src/logfile.ts
  src/sequenceView.ts
  src/textView.ts
Labels: enhancement

#153 VSCODE-NLP-084 display orphan passes in outputView
  package.json
  src/outputView.ts
  src/sequence.ts
Labels: enhancement

#154 VSCODE-NLP-085 remove vsocde from dependencies for compilation
  package.json
Labels: bug

#161 VSCODE-NLP-086 Misc fixes
  package.json
  src/logfile.ts
  src/sequenceView.ts
  syntaxes/seq.tmLanguage.json
Labels: bug

#163 VSCODE-NLP-088 Searches now can include non-alpha characters
  src/findFile.ts
Labels: enhancement

#164 VSCODE-NLP-089 Log generation messages fixed
  src/status.ts
Labels: bug

#168 VSCODE-NLP-091 Rename and NLP Logo
  README.md
  package.json
  resources/NLPppLogo.png
  resources/dark/rename.svg
  resources/light/rename.svg
  src/analyzerView.ts
  src/dirfuncs.ts
  src/findView.ts
  src/logView.ts
  src/outputView.ts
  src/sequenceView.ts
  src/textView.ts
Labels: enhancement

#169 VSCODE-NLP-092 Changes for publishing in Microsoft Marketplace
  package.json
Labels: code improvement

#170 VSCODE-NLP-093 Update README.md
  README.md
Labels: enhancement

#172 VSCODE-NLP-095 Updated the Readme to include sample analyzer information
  README.md
  package.json
Labels: code improvement
