Repository VisualText/vscode-nlp, pull requests merged in 2021-02, with the labels that each got.

#207 VSCODE-NLP-120 Updated README to include Linux, Windows, MacOS
  README.md
Labels: enhancement

#208 VSCODE-NLP-121 Added nlp engine for all three platforms
  .vscodeignore
  package.json
  src/dirfuncs.ts
  src/nlp.ts
  src/sequence.ts
  src/visualText.ts
Labels: enhancement

#210 VSCODE-NLP-122 Active fix and version 1 fixes
  package.json
  resources/dark/dna-grayed.svg
  resources/light/dna-grayed.svg
  src/dirfuncs.ts
  src/sequence.ts
  src/sequenceView.ts
  src/visualText.ts
Labels: bug

#212 VSCODE-NLP-124 Fixing version 1
  src/dirfuncs.ts
  src/nlp.ts
  src/visualText.ts
Labels: bug, enhancement

#213 VSCODE-NLP-125 Version one release with the nlp-engine built in
  CHANGELOG.md
  README.md
  package.json
Labels: enhancement

#215 VSCODE-NLP-126 add duplicate line to rule editor
  package.json
  src/command.ts
  src/nlp.ts
Labels: enhancement
